### ISSUE TITLE
Details about the pretrained net

### ISSUE THREAD

**Issue by expectopatronum** [arity-r/ChimeraNet#16]
Hi,
thanks for implementing the chimera network! Could you explain what data the pretrained model was trained on? What are the sources it separates? What does the 120 in the name stand for? Do you have more pretrained models that you can share?

Thanks and best regards
Verena

**Comment by leichtrhino** [comment]
Hello,

The model I showed on `README` separates into voice and music components. The dataset used was as follows.
1. voice
   - `VoxCeleb 1` (both dev and test)
   - `MedleyDB` (vocal)
   - voice segments manually obtained from some Japanse anime
2. music
   - `MedleyDB` (accompaniment)
   - `Clean MIDI subset` of `The Lakh MIDI Dataset v0.1`

The number `120` stands for the training epoch. During one epoch, 1600 audio segments were used for the training process. The length of the segment is two seconds.

Also, I trained ChimeraNet on the `DSD100` dataset and uploaded it here.

https://drive.google.com/open?id=1KxH5juFihsNpJPXtYO6P3icTAzCpNd5d

The splits I used were both training and validation splits, so the trained model is not suitable for evaluating ChimeraNet.

Thanks.
