### ISSUE TITLE
sample_rate argument

### ISSUE THREAD

**Issue by HIN0209** [arity-r/ChimeraNet#2]
Hello again! I have tried my own wav files with the following characteristics shown by the soxi command. With the wav files, chimeranet-train.py threw an error when I set the --sr argument to either 44100 or 22050 (the error message >> Error when checking input: expected input_1 to have shape (64, 259) but got array with shape (64, 188)), whereas the default sampling rate of 16,000 just works fine to train. I am wondering whether higher than 16,000 SR is accepted for training (or higher SR makes any sense to be used in your system). Thanks.

Input File     : 'XXX.wav'
Channels       : 1
Sample Rate    : 44100
Precision      : 16-bit
Duration       : 00:00:02.00 = 88200 samples = 150 CDDA sectors
File Size      : 184k
Bit Rate       : 734k
Sample Encoding: 16-bit Signed Integer PCM

**Comment by leichtrhino** [comment]
I forgot to add `sr` parameter to `generate_data`. Thanks for reporting!

**Comment by HIN0209** [comment]
That is informative. Thank you.
